"""The interview's approval rules become settings (audit B-01, 2026-10-08).

WHAT WAS WRONG. The sign-up interview asks who signs off on what, and the
founder answers precisely: "Sales can confirm orders up to 5 lakh — above that,
me", "Kavitha in HR approves leave", "purchases over 1 lakh come to me". The
blueprint kept those answers as free text on `tenant.approval_rules` and
nothing ever read them. The operating model was generated by a separate call
that never saw them, so every order's confirmation became owner-only, every
team's leave went to the owner, and the money threshold stayed a generic
50,000 — the owner was made to approve everything they had just delegated.

WHAT THIS DOES. After the operating model exists (so there are real team and
stage keys to point at), one AI call maps each rule onto a setting the app
enforces, and the result is validated against those keys before anything is
written:

  stage_limit      pipeline.approval_stage = stage, and
                   pipeline.approval_delegate = {role: team, up_to: amount}
                   (services/workflow_engine.advance lets that team move a card
                   into the stage itself while its value is within the limit)
  owner_stage      pipeline.approval_stage = stage (owner only, as before)
  leave_approver   tenant.leave_approver_teams = {"*" or team: approver team}
                   (services/leave resolves it to a member of that team)
  money_threshold  tenant.high_value_threshold = amount,
                   tenant.require_owner_signoff = True
  note             kept, shown to the owner as "noted — not a setting yet"

Every rule ends up in `tenant.approval_rules_applied` with what it became, so
Settings can say it plainly. Re-running is safe: the same rules give the same
settings.
"""
import json
from typing import Any, Dict, List, Optional

from core import _extract_json, claude_chat, db, logger, model_for, new_id, now_iso
from emergentintegrations.llm.chat import UserMessage
from prompts import render

KINDS = ("stage_limit", "owner_stage", "leave_approver", "money_threshold", "note")


def _money(v) -> Optional[float]:
    try:
        x = float(v)
    except (TypeError, ValueError):
        return None
    return x if x > 0 else None


def validate_actions(raw: Any, *, rules: List[dict], teams: List[dict], pipelines: List[dict]) -> List[dict]:
    """Keep only actions that point at things this company really has. Any rule
    left without a valid action becomes a note, so every rule is accounted for."""
    team_keys = {t.get("key") for t in teams if t.get("key") and t.get("key") != "owner"}
    stages = {p.get("key"): {s.get("key") for s in (p.get("stages") or []) if isinstance(s, dict)}
              for p in pipelines if p.get("key")}
    names = [str(r.get("name") or "").strip() for r in rules if str(r.get("name") or "").strip()]
    out = []
    acts = raw.get("actions") if isinstance(raw, dict) else raw if isinstance(raw, list) else []
    for a in acts or []:
        if not isinstance(a, dict) or a.get("kind") not in KINDS:
            continue
        rule = str(a.get("rule") or "").strip()
        if rule not in names:
            # tolerate case drift, never invent a rule
            rule = next((n for n in names if n.lower() == rule.lower()), "")
            if not rule:
                continue
        k = a["kind"]
        if k in ("stage_limit", "owner_stage"):
            if a.get("pipeline") not in stages or a.get("stage") not in stages[a.get("pipeline")]:
                continue
            item = {"rule": rule, "kind": k, "pipeline": a["pipeline"], "stage": a["stage"]}
            if k == "stage_limit":
                up_to = _money(a.get("up_to"))
                if a.get("team") not in team_keys or not up_to:
                    continue
                item.update(team=a["team"], up_to=up_to)
            out.append(item)
        elif k == "leave_approver":
            if a.get("team") not in team_keys:
                continue
            for_teams = [x for x in (a.get("for_teams") or ["*"]) if x == "*" or x in team_keys] or ["*"]
            out.append({"rule": rule, "kind": k, "team": a["team"], "for_teams": for_teams})
        elif k == "money_threshold":
            amt = _money(a.get("amount"))
            if amt:
                out.append({"rule": rule, "kind": k, "amount": amt})
        else:
            out.append({"rule": rule, "kind": "note", "reason": str(a.get("reason") or "")[:160]})
    covered = {a["rule"] for a in out}
    for n in names:
        if n not in covered:
            out.append({"rule": n, "kind": "note", "reason": "No setting matches this rule yet."})
    return out


async def structure_approval_rules(rules: List[dict], teams: List[dict], pipelines: List[dict]) -> List[dict]:
    """One AI call: the founder's rules -> validated actions on real keys."""
    rules = [r for r in (rules or []) if isinstance(r, dict) and str(r.get("name") or "").strip()]
    if not rules:
        return []
    ctx = {
        "rules": [{"name": r.get("name"), "description": r.get("description") or ""} for r in rules],
        "teams": [{"key": t.get("key"), "label": t.get("label")} for t in teams if t.get("key") and t.get("key") != "owner"],
        "pipelines": [{"key": p.get("key"), "label": p.get("label"),
                       "stages": [{"key": s.get("key"), "label": s.get("label")} for s in (p.get("stages") or [])
                                  if isinstance(s, dict)]} for p in pipelines if p.get("key")],
    }
    chat = claude_chat(task="generators.approval_rules", session_id=f"apprules-{new_id()}",
                       system_message=render("generators.approval_rules")).with_model(*model_for("generators.approval_rules"))
    try:
        resp = await chat.send_message(UserMessage(text=json.dumps(ctx, ensure_ascii=False)))
        data = _extract_json(resp) or {}
    except Exception as e:  # noqa: BLE001 — a failed call leaves every rule a note
        logger.error(f"structure_approval_rules failed: {e}")
        data = {}
    return validate_actions(data, rules=rules, teams=ctx["teams"], pipelines=ctx["pipelines"])


def _inr(x: float) -> str:
    """Rupees in Indian grouping: 500000 -> 5,00,000."""
    from services.invoicing import _money
    return _money(x, "INR")[:-3]


def _label(items, key, default=""):
    return next((x.get("label") for x in items if x.get("key") == key), default or key)


def describe(action: dict, teams: List[dict], pipelines: List[dict]) -> str:
    """What the rule became, in the owner's words."""
    k = action["kind"]
    if k in ("stage_limit", "owner_stage"):
        p = next((x for x in pipelines if x.get("key") == action["pipeline"]), {})
        stage = _label(p.get("stages") or [], action["stage"])
        where = f"{p.get('label') or action['pipeline']} › {stage}"
        if k == "owner_stage":
            return f"Only you can move work into {where}."
        return (f"{_label(teams, action['team'])} can move work into {where} up to "
                f"₹{_inr(action['up_to'])}; above that it comes to you.")
    if k == "leave_approver":
        who = _label(teams, action["team"])
        scope = "every team" if "*" in action["for_teams"] else ", ".join(_label(teams, t) for t in action["for_teams"])
        return f"{who} approves leave for {scope}."
    if k == "money_threshold":
        return f"Spending of ₹{_inr(action['amount'])} or more comes to you to sign off."
    return "Noted — there is no setting for this yet, so Dex keeps it as a note."


async def apply_actions(tenant_id: str, actions: List[dict]) -> List[dict]:
    """Write the validated actions onto the tenant. Returns the per-rule summary."""
    t = await db.tenants.find_one({"id": tenant_id}, {"_id": 0, "roles": 1, "operating_model": 1,
                                                      "approval_rules": 1})
    t = t or {}
    teams = t.get("roles") or []
    om = t.get("operating_model") or {}
    pipelines = om.get("pipelines") or []
    sets: Dict[str, Any] = {}
    leave_map: Dict[str, str] = {}
    om_changed = False
    for a in actions:
        if a["kind"] in ("stage_limit", "owner_stage"):
            for p in pipelines:
                if p.get("key") == a["pipeline"]:
                    p["approval_stage"] = a["stage"]
                    if a["kind"] == "stage_limit":
                        p["approval_delegate"] = {"role": a["team"], "up_to": a["up_to"]}
                    else:
                        p.pop("approval_delegate", None)
                    om_changed = True
        elif a["kind"] == "leave_approver":
            for team in a["for_teams"]:
                leave_map[team] = a["team"]
        elif a["kind"] == "money_threshold":
            sets["high_value_threshold"] = a["amount"]
            sets["require_owner_signoff"] = True
    if om_changed:
        sets["operating_model.pipelines"] = pipelines
    if leave_map:
        sets["leave_approver_teams"] = leave_map
    descs = {r.get("name"): r.get("description") or "" for r in (t.get("approval_rules") or []) if isinstance(r, dict)}
    # One line per RULE: a rule can become a setting AND leave a part that is
    # only a note ("up to 5 lakh" is a setting, "no discount above 5%" is not).
    summary, seen = [], {}
    for a in actions:
        row = seen.get(a["rule"])
        if row is None:
            row = {"rule": a["rule"], "description": descs.get(a["rule"], ""), "kinds": [], "settings": [], "notes": []}
            seen[a["rule"]] = row
            summary.append(row)
        row["kinds"].append(a["kind"])
        if a["kind"] == "note":
            row["notes"].append(a.get("reason") or "")
        else:
            row["settings"].append(describe(a, teams, pipelines))
    for row in summary:
        row["setting"] = bool(row["settings"])
        row["kind"] = next((k for k in row["kinds"] if k != "note"), "note")
        notes = [n for n in row.pop("notes") if n]
        row["became"] = " ".join(row["settings"]) or describe({"kind": "note"}, teams, pipelines)
        row["still_a_note"] = notes[0][:200] if row["settings"] and notes else ""
        row.pop("kinds")
    sets["approval_rules_applied"] = summary
    sets["approval_rules_applied_at"] = now_iso()
    await db.tenants.update_one({"id": tenant_id}, {"$set": sets})
    return summary


async def apply_interview_rules(tenant_id: str) -> List[dict]:
    """Structure + apply this company's interview rules. Safe to re-run."""
    t = await db.tenants.find_one({"id": tenant_id}, {"_id": 0, "roles": 1, "operating_model": 1,
                                                      "approval_rules": 1})
    rules = (t or {}).get("approval_rules") or []
    if not rules:
        return []
    actions = await structure_approval_rules(rules, (t or {}).get("roles") or [],
                                             ((t or {}).get("operating_model") or {}).get("pipelines") or [])
    return await apply_actions(tenant_id, actions)
